### ISSUE TITLE
Add TCP and IMCP support.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1004]
I know that you do not see py-IPv8 as replacing TOR, but I do. py-IPv8 solves the main problem with Tor, that is, the Tor Directory Authorities. I remember when a DDOS attack took out all the v3 directory authorities because someone wanted to delay the rollout of v3 onion nodes, which provided enhanced anonymity. py-IPv8 is also superior to I2P because I2P has no way to discourage leechers who do not provide to the network, but in order for IPv8 to fully replace Tor, it would need to support TCP so users can access webpages too. IMCP would also be necessary to provide anonymity, because clients and servers need IMCP to coordinate traffic and handle error messages, and not to forget pings, which are used to test if the internet connection is functioning properly.

**Comment by synctext** [comment]
Thnx @Destroyinator69420 The Tor ddos event was quite something to read about. There having a little cyberware between competing darknet markets, https://www.reddit.com/r/TOR/comments/kualce/all_v3_onion_addresses_down_after_attack_on_the/

interesting bit:
```
You will currently not be able to access any v3 onion addresses, what is happening is unknown, but it is potentially
a huge attack on the entire network. Earlier today I made a post outlining consequences I would be putting into place
to deter markets from funding DDoS attacks against each other, as the potential to scale and completely kill every node
on the network is a very real potential outcome.
```

### Web3 = Bittorrent + Trustchain
To finally answer your question, support for TCP is not on our roadmap. We specifically want to create an academically pure, trustworthy alternative for Big Tech and the old web in general. We will not support Javascript and TCP, because then we re-enable all the monopolies and flaws of the past. So we might be quite naive about this, but we are trying to make it work.
