### ISSUE TITLE
Allow clients to split their traffic between multiple paths for increased anonymity.

### ISSUE THREAD

**Issue by Destroyinator69420** [Tribler/py-ipv8#1005]
I was testing a project with a similar goal to yours called lokinet. (https://lokinet.org) One of its distinguishing features that sets it apart from other protocols with a similar goal is its ability to split traffic between multiple service nodes for better load balancing, fault tolerance, and increased anonymity. Considering the consumer P2P nature of py-IPv8, I think that this is necessary to continue the connection if one of the proxies logs off. It would also make it much harder to to spy on users, as more than one circuit would need to be compromised in order to successfully spy on users, I recommend six circuits when taking into consideration the limitations of python, but lokinet could have as much as 30 circuits at any one time.

**Comment by qstokkink** [comment]
Hi, thanks for your interest in IPv8. This is a feature we already support. Our anonymization overlay can be configured to make "any" number (as long as your machine supports it) of circuits available:

https://github.com/Tribler/py-ipv8/blob/7a94e31c1036b7d13491dc63a8e8d55ed34f0c7d/ipv8/messaging/anonymization/community.py#L52-L53

By default IPv8 will make between 1 and 8 circuits available to you. In our downstream project Tribler, you get [between 3 and 10 circuits](https://github.com/Tribler/tribler/blob/3c35d2ee8fc73f57d994070386f223ded91c67fb/src/tribler-core/tribler_core/modules/ipv8_module_catalog.py#L166-L167).

You're welcome to change the minimum circuits to 6 for your own use. However, these starting values fit typical use of our applications. The trade-off is that the more circuits you need to make, the longer you need to wait before you can start using them and the more CPU power you need.

Since the original feature request is already available, I'll close this issue. However, feel free to ask if you have any questions.

**Comment by Destroyinator69420** [comment]
I was not aware, there was not a lot of documentation on your readthedocs page about how the protocol actually operated. I think that py-IPv8 could eventually compete with Tor, but it would need TCP support in order to do it. If you wanted to make py-IPv8 superior to Tor, you could add IMCP support for anonymous pings and network configuration. However, I am worried about attacks on the py-IPv8 trustchain that could de-anonymize users. I am also worried about malicious exit nodes which tamper with traffic, the riffle hybrid verifiable shuffle and riffle authentication encryption solved this, but it would be difficult to implement in python due to python being slower than go, which riffle is programmed in.

**Comment by qstokkink** [comment]
> However, I am worried about attacks on the py-IPv8 trustchain that could de-anonymize users.

I share your concerns. This is why we are phasing out Trustchain (it has even already been removed from this repository). We are moving toward an even more peer-to-peer solution instead of a peer-to-everyone solution. More local agreements, less network-wide broadcasts!

We're also trying to get rid of exit-node-to-Internet communication. For this we use the "hidden services" protocol: no need for riffle. The hidden services protocol offers end-to-end encryption, so you don't need to trust exit nodes.
