### ISSUE TITLE
Communication between nodes behind Symmetric NAT

### ISSUE THREAD

**Issue by teddyk251** [Tribler/py-ipv8#1083]
I wanted to be able to send messages between nodes that are behind symmetric NAT and the example code is not working. What are the requirements for nodes to be able to communicate when behind symmetric NAT?

**Comment by qstokkink** [comment]
You have two options:

1. You can send broadcasts over the local network by using the `UDPBroadcastBootstrapper` configuration. The downside of this, is that it uses a lot of network traffic (the optimization to slow it down is still an open issue #1076). This is why it is disabled by default.
2. You can also run your own bootstrap node and define its address in a `DispersyBootstrapper`, or extend the default configuration for it if you have the default bootstrapper specified. I've described this in more detail here: https://github.com/Tribler/py-ipv8/issues/971#issuecomment-806447155

**Comment by teddyk251** [comment]
The scenario I'm trying is one node is on a machine that is behind symmetric NAT and the other node is on a different machine with a public IP address. I tried the second approach and modified bootstrap configuration as specified here[](https://github.com/Tribler/py-ipv8/issues/971#issuecomment-806447155) for the node running behind NAT but I'm getting inconsistent results. Sometimes I'm able to discover the other node and send a message but even if that's the case it takes a very long time until the peer is discovered. In another case, no nodes are discovered and I'm unable to communicate. The tracker_plugin script is running alongside the node behind NAT.

**Comment by qstokkink** [comment]
If you want to quickly connect to a well-known address you can use `Community.walk_to()`. Otherwise, you are depending on our random introduction mechanism, which--as you mentioned--can take a long time to connect to any particular peer.

Our default protocols are great when you have a large number of peers in a network and you want a random selection. They are less great if you have a very small amount of network participants.

**Comment by teddyk251** [comment]
I've added some extra nodes to the community and I'm now getting better performance. I tried running the same test when the nodes are on different machines and different networks but both are behind a symmetric nat. For this scenario, I'm not getting a single working test, all my attempts are failing. Is it possible to communicate when both nodes are behind NAT and they are on different machines with different networks?

**Comment by qstokkink** [comment]
There are definitely situations where NATs _really_ don't want to talk to each other. We've done some research on this a few years back (copied from the paper Dispersy Bundle Synchronization. [_Niels Zeilemaker, Boudewijn Schoon and Johan Pouwelse_. 2013.](https://d2k0ddhflgrk1i.cloudfront.net/EWI/Over%20de%20faculteit/Afdelingen/Software%20Technology/Distributed%20Systems/Technical%20Reports/2013/PDS-2013-002.pdf)):

![Dispersy Bundle Synchronization](https://user-images.githubusercontent.com/3630389/151325153-66b2f278-6244-405f-a8bd-8217d6e58a98.png)

Your setup might be part of the unlucky configurations. If you insist on these particular machines talking to each other, you can try enabling anonymization for your Community (`anonymize=True`). This forces the connections to be proxied over a different machine's NAT (which probably has a higher success rate). Otherwise, I'd suggest forwarding information over the nodes that can interconnect.

**Comment by teddyk251** [comment]
Thank you for your support, I've solved the issue I had.

**Comment by qstokkink** [comment]
You're welcome. Have fun playing around with IPv8 👍 

I'll close this issue for now then: if you have other questions feel free to open another issue or reopen this one.
