### ISSUE TITLE
Basic tutorial does not work

### ISSUE THREAD

**Issue by bacox** [Tribler/py-ipv8#1208]
If you run one of the basic tutorials ([https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html](https://py-ipv8.readthedocs.io/en/latest/basics/overlay_tutorial.html)) using the latest release, it will crash. In this case, the function `run_forever` is not in the latest release. There is a mismatch between de version of the docs online and the latest release.

I think the following points are of interest:

1. The documentation on _readthedocs_ is based on the main branch of the repo and not on the latest released version. It would be nice if the documentation of _readthedocs_ is based on the latest release.
2. It would also be great if you can select the version in _readthedocs_.

**Comment by qstokkink** [comment]
Thanks for the feedback. I'll check if I can instruct ReadTheDocs to save historical documentation. If it seems like too much overhead, this idea will be dropped: the bleeding edge code is _usually_ compatible with the latest release anyway.

**Comment by mg98** [comment]
I also encountered this. 

I think if we just
```
git checkout 2.11
git checkout -b stable
git push -u origin stable
```

the docs would
- default to the latest release (`stable`)
- give you the option to select historical releases
- still show `latest`

https://docs.readthedocs.io/en/stable/versions.html just

**Comment by qstokkink** [comment]
@mg98 thanks for the suggestion: new branches are not an option for us but we do support/have historical tags, which your linked docs suggest are also supported.

**Comment by qstokkink** [comment]
As it turns out, I can have old versions built with a single click:
![versions](https://github.com/Tribler/py-ipv8/assets/3630389/63e06f48-af1a-4746-a29d-2665b831ac15)

However, old versions are not compatible with the new ReadTheDocs build system and they fail to build. So, unless I do revisionist history and push new settings to ancient versions of IPv8 by force-pushing (which is a NO-NO unless it is a life-or-death situation), I'll only be able to store old documentation from the current version (2.12) onward. Not ideal, but, with that I consider this issue solved.

By the way, here is 2.12: https://py-ipv8.readthedocs.io/en/2.12/
