### ISSUE TITLE
Flexible interval for register task

### ISSUE THREAD

**Issue by grimadas** [Tribler/py-ipv8#840]
`register_task` now uses `interval_runner` that has fixed interval. 
A register task with flexible interval is required for my project. There might be several ways to support that: 

 - Change interval  runner `sleep interval` with `sleep task.interval`. 

- Change interval to a `Callable` to support any function.

**Comment by qstokkink** [comment]
@egbertbouman as you've done the most with the low-level `asyncio` and `TaskManager` stuff: what is your opinion?

**Comment by egbertbouman** [comment]
The `interval` keyword argument is just a shortcut to prevent us from having to write the same loop over and over gain. If it's just for occasional use, I'd recommend creating the `Task` yourself. For example:

```python
class SomeComponent(TaskManager):

    def __init__(self):
        super(SomeComponent, self).__init__()
        self.register_task('increasing_interval', ensure_future(self.increasing_interval()))

    async def increasing_interval(self):
        counter = 0
        while True:
            await sleep(counter)
            counter += 1
```

**Comment by qstokkink** [comment]
@egbertbouman thanks! I don't think we can really improve upon your example with additional `register_task` magic. If anything, if we add dynamic intervals to `register_task`, the user code will probably only get uglier.

@grimadas do you have any use-case that is not covered by @egbertbouman's solution? Otherwise, we will probably not implement this feature.

**Comment by grimadas** [comment]
Thanks,  that works
