### ISSUE TITLE
Message id based attacker detection

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#873]
Messages in IPv8 have very clear behavioral patterns. For instance, if a peer starts sending `245` messages without being sent a `246` first, there is something wrong. If more than 3 `246` messages are being received from a single peer per second, they are not sticking to the protocol.

There are many suspect behaviors on the message layer (based on the message ids) that I know by heart and I need to check by hand. We _can_, however, use some form of machine learning to detect suspicious behavior on the messaging layer.

If we do implement something like this. We need to make sure to stick with these rules, we learned the hard way:

 - Only remove peers when we have enough peers already (i.e. when we hit the maximum amount of peers for that community).
 - Allow manual marking of some message ids as not subject to analysis (particularly data stream messages should not be analyzed, control messages should).

**Comment by devos50** [comment]
You could even consider applying a form of federated learning here to train a classifier (attacker vs non-attacker), where the training data is the sequence of incoming/outgoing messages (with timestamps). Users locally train the model and share the model parameters with others. The main challenge is to prevent attackers from poisoning the model and incorrectly classify an honest peer as malicious. This approach would also protect privacy since users do not directly share all their network messages with others.

**Comment by qstokkink** [comment]
Closing this for the following reasons:

 - IPv8 is a networking/overlay framework, not a machine learning framework. This is out of our scope.
 - This feature can be implemented outside of IPv8 without modifying the IPv8 core. 
 - Porting this to other platforms (i.e., Android) will be a nightmare.
 - Not all devices running IPv8 may be able to handle full-on machine learning (both in terms of CPU and storage required to store a fully pretrained model). This is niche functionality, not common core.
